### ISSUE TITLE
Fused rotary monkeypatch doesn't work for the newest `transformers`

### ISSUE THREAD

**Issue by koute** [whyNLP/tinyllama#2]
Before: https://github.com/huggingface/transformers/blob/v4.35.2/src/transformers/models/llama/modeling_llama.py#L201

After: https://github.com/huggingface/transformers/blob/v4.38.2/src/transformers/models/llama/modeling_llama.py#L185

**Comment by why-in-Shanghaitech** [comment]
Thank you for pointing this out! Yes, since the `transformers` library is actively updating, the codes require some modifications for newer versions. For example, in newer versions, the way to call Flash Attention 2 changes to

```diff
- model = AutoModelForCausalLM.from_pretrained("TinyLlama/TinyLlama-1.1B-intermediate-step-955k-token-2T", use_flash_attention_2=True)
+ model = AutoModelForCausalLM.from_pretrained("TinyLlama/TinyLlama-1.1B-intermediate-step-955k-token-2T", attn_implementation="flash_attention_2")
```

That's why I added `transformers == 4.35.2` in the `requirements.txt`. Maybe I'll update the instructions when I'm available in the future.

**Comment by why-in-Shanghaitech** [comment]
Thanks again for your issue! I have updated the repo. Feel free to leave any comments.

**Comment by koute** [comment]
Thanks!
